---
deployment:
  tasks:
    - export DEPLOYPATH=/home/colettefleury/public_html/
    - /bin/cp public/data.json $DEPLOYPATH
    - /bin/cp -R public/images $DEPLOYPATH
    - /bin/cp -R public/sources $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R dist $DEPLOYPATH
